### ISSUE TITLE
Nasıl Kuracağım

### ISSUE THREAD

**Issue by earltt** [serozr/anti-gamemode#1]
merhaba bu datapackı nasıl kuracağım arkadaşlarımla oynuyoruz ve gamemodu oplere kapatmak istiyorum yardımcı olur musun

**Comment by serozr** [comment]
indirdiğiniz zip dosyasını **.minecraft/saves/(world)/datapacks** kısmına atın.

[İndirme Linki](https://github.com/serozr/anti-gamemode/releases/download/1.1.0/anti-gamemode.zip)
